In [1]:
import psutil

def check_if_running(process_name):
    running = False
    for proc in psutil.process_iter(["name"]):
        if process_name in proc.info["name"]:
            running = True
            break
    return running

ollama_running = check_if_running("ollama")

if not ollama_running:
    raise RuntimeError(
        "Ollama not running. Launch ollama before proceeding."
)
print("Ollama running:", check_if_running("ollama"))

Ollama running: True


## Interact with Ollama via API

In [14]:
import urllib.request
import json

def query_model(
    prompt, 
    model="llama3", 
    url="http://localhost:11434/api/chat"
):
    data = {             #1
        "model": model,
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "options": {         #2
            "seed": 123,
            "temperature": 0,
            "num_ctx": 2048
        }
    }


    payload = json.dumps(data).encode("utf-8")    #3
    request = urllib.request.Request(                       #4
        url,                                                #4
        data=payload,                                       #4
        method="POST"                                       #4
    ) #4

    request.add_header("Content-Type", "application/json")   #4

    response_data = ""
    with urllib.request.urlopen(request) as response:   #5
        while True:
            line = response.readline().decode("utf-8")
            if not line:
                break
            response_json = json.loads(line)
            response_data += response_json["message"]["content"]

    return response_data

In [15]:
model = "gemma3:270m"
result = query_model("What is the capital of France?", model)
print(result)

The capital of France is Paris.



In [16]:

result = query_model("What do snails eat?", model)
print(result)

Snails are primarily carnivorous, meaning they eat plants and other organic matter. They are known for their ability to digest a wide variety of food, including:

*   **Leaves:** They are the primary food source for many snails.
*   **Roots:** They can absorb nutrients from the soil.
*   **Fruits and Vegetables:** They can also eat fruits and vegetables.
*   **Seeds:** They can also eat seeds.
*   **Other Organic Matter:** They can also eat other organic matter.




In [17]:
import torch
torch.cuda.is_available()

False

In [18]:
from torch import tensor
tensor2d = tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
print(tensor2d.shape)

torch.Size([2, 3])


Reshape the tensor into 3x2

In [20]:
print(tensor2d.reshape(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


However, note that the more common command for reshaping tensors in PyTorch is .view()

In [21]:
print(tensor2d.view(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


Similar to .reshape and .view, in several cases, PyTorch offers multiple syntax options for executing the same computation. PyTorch initially followed the original Lua Torch syntax convention but then, by popular request, added syntax to make it similar to NumPy. (The subtle difference between .view() and .reshape() in PyTorch lies in their handling of memory layout: .view() requires the original data to be contiguous and will fail if it isn’t, whereas .reshape() will work regardless, copying the data if necessary to ensure the desired shape.)

Matrix multiplication

In [22]:
print(tensor2d.matmul(tensor2d.T)) # way 1
print(tensor2d @ tensor2d.T) # way 2

tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])


## Interact with LM Studio

In [29]:
import lmstudio as lms

model = lms.llm("gemma-3-270m-it")
result = model.respond("What is the meaning of life?")

print(result)


The meaning of life is a question that has been pondered by humans for millennia. There's no single, universally accepted answer. 

Different philosophies and religions offer varying perspectives on this fundamental inquiry. Some common answers include:

*   **Religion:** Many religions offer answers through faith or belief in a higher power, guiding individuals towards a fulfilling life.
*   **Philosophy:** Exploring the meaning of existence through philosophical thought can lead to insights into morality, ethics, and the nature of reality.
*   **Personal Growth:** Finding meaning through personal development, learning, and experiencing the world is often seen as a significant aspect of a meaningful life.
*   **Relationships:** Connecting with others and building meaningful relationships can provide purpose and support.

Ultimately, what constitutes a meaningful life is subjective and depends on individual values, beliefs, and experiences.


In [30]:
import lmstudio as lms

with lms.Client() as client:
    model = client.llm.model("microsoft/phi-4-mini-reasoning")
    result = model.respond("What is the meaning of life?")

    print(result)


<think>

Okay, so I need to figure out what the meaning of life is. Hmm, where do I start? The user mentioned that I'm Phidot, but maybe they're actually asking me, the AI, named Phi developed by Microsoft. Wait, no, the user's name is Phi, and they want my answer. Let me focus on the question itself.

The meaning of life has been a big question in various fields—religion, philosophy, science, even popular culture. Different people have different answers based on their beliefs or knowledge. Let's break this down step by step.

First, from a philosophical standpoint. Existentialists like Sartre might say life has no inherent meaning, and we create our own through choices. Contrast that with religions that often prescribe a purpose, like Christianity's idea of serving God or achieving salvation.

Then there's the scientific angle. Biologists might focus on survival and reproduction as biological imperatives. Some even look at life's origin, like abiogenesis, but that's more about how lif

You need to download the `nomic-embed-text:latest` model before run in it.

In [8]:
import ollama
vector = ollama.embeddings(model='nomic-embed-text:latest', prompt='The sky is blue because of rayleigh scattering')
print(len(vector.embedding))

768
